name: CI/CD Mercadinho

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Atualizar pip
        run: python -m pip install --upgrade pip

      - name: Instalar dependências
        run: pip install -r requirements.txt

      - name: Rodar testes com relatório
        run: pytest --html=report.html --self-contained-html

      - name: Salvar relatório de testes
        uses: actions/upload-artifact@v4
        with:
          name: relatorio-testes
          path: report.html

  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Build
        run: echo "Build realizado com sucesso"

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        run: echo "Deploy realizado com sucesso"